---
- name: Install module PHP for Apache or Nginx
  apt: name=libapache2-mod-php state=present
  
- name: Install PHP 7.3 Debian 10
  apt: name=php state=present

- name: Install dependencies PHP
  apt: name=php-common state=present

- name: Install extensions PHP
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - php-cli
    - php-fpm
    - php-json
    - php-pdo
    - php-mysql
    - php-zip
    - php-gd
    - php-mbstring
    - php-curl
    - php-xml
    - php-pear
    - php-bcmath
